### ISSUE TITLE
Only 1 node displayed for threadripper CPUs

### ISSUE THREAD

**Issue by terroreek** [ocerman/zenmonitor#1]
When using Zenmonitor it only displays the temps, voltages and from only one threadripper node.

the output from sensors
`zenpower-pci-00c3
Adapter: PCI adapter
SVI2_Core:    +1.00 V  
SVI2_SoC:     +0.01 V  
Tdie:         +35.6°C  (high = +70.0°C)
Tctl:         +62.6°C  
SVI2_P_Core:  60.27 W  
SVI2_P_SoC:    0.00 W  
SVI2_C_Core: +60.27 A  
SVI2_C_SoC:   +0.00 A  

zenpower-pci-00cb
Adapter: PCI adapter
SVI2_Core:    +1.36 V  
SVI2_SoC:     +0.01 V  
Tdie:         +33.9°C  (high = +70.0°C)
Tctl:         +60.9°C  
SVI2_P_Core:  14.10 W  
SVI2_P_SoC:    0.00 W  
SVI2_C_Core: +11.43 A  
SVI2_C_SoC:   +0.00 A  
`
what you see in zenmonitor

![2019-06-20_19-27](https://user-images.githubusercontent.com/7308768/59887484-81e01c80-9391-11e9-965c-43df8b72cdc8.png)

**Comment by ocerman** [comment]
Thanks for your report, I will look at it.

**Comment by ocerman** [comment]
@terroreek Commit 1d8cfab2924b937059fab9a15a94af410772234d should fix that. Could you try it again?

**Comment by terroreek** [comment]
Yep working now!

**Comment by KeithMyers** [comment]
I just noticed.  Don't know how I missed it.  The labels for the Tdie and Tctrl Nodes are swapped for the correct values.  Zenpower driver has them correct in sensors, but Zen Monitor does not.

The screen image in the previous post shows it too.  Here is my screen shot.
![Screenshot of Zenmonitor_1 41](https://user-images.githubusercontent.com/31547850/84966780-39079480-b0c7-11ea-8249-e14c44e87711.png)
