### ISSUE TITLE
An option to display index of core instead of core_id?

### ISSUE THREAD

**Issue by j1warren** [ocerman/zenmonitor#14]
![Screenshot](https://user-images.githubusercontent.com/46167694/72201648-481a5480-344e-11ea-8ebf-a259899bbf47.png)

So, as I undersntand now it shows core_id, but maybe we need a flag to display the index, as in htop and lscpu?

**Comment by j1warren** [comment]
going back to tag/1.2 fixes this.
I think it's 5408b21e7

**Comment by j1warren** [comment]
Oh, there are missing cores on the screenshot, so overall there are correct 12 cores, but they have wrong id's.

**Comment by ocerman** [comment]
Yes, I agree that core_id may be confusing. I will add this option.

**Comment by ocerman** [comment]
Core index is now displayed by default. To display core_id run `zenmonitor --coreid`
