### ISSUE TITLE
Enlarge the window on start so that all rows are visible.

### ISSUE THREAD

**Issue by j1warren** [ocerman/zenmonitor#15]
![Screenshotzen](https://user-images.githubusercontent.com/46167694/73132208-ad09a900-400f-11ea-92b0-15559087a8dc.png)

Now it always starts like here with fixed size. GTK 3.28.

PS Should have in mind that the number of rows will be different if started with or without the access to MSR (sudo).
PPS Maybe add a Capabilities workaround note in README?
`$ sudo setcap cap_sys_rawio,cap_dac_read_search+ep ./zenmonitor` seems suffice.

**Comment by ocerman** [comment]
Thanks for your report. It should be fixed in the latest version.
I have also added capabilities workaround into readme.

**Comment by j1warren** [comment]
@ocerman, thank you for looking into it!
In my case (see screen shot in #17) last 3 rows are still left out, so the scrollbar appears again.
values from the end of resize_to_treeview()
  r.height = 327
  uiHeight = 23
  cellHeight = 21
  rows = 35`

**Comment by ocerman** [comment]
@j1warren seems like cellHeight is not correct. Can you tell me which distro and GTK theme are you using?

**Comment by j1warren** [comment]
Ubuntu 18.04, gnome 3.28.2
https://github.com/lassekongo83/plano-theme

**Comment by ocerman** [comment]
@j1warren can you try it again? It should be fixed.

**Comment by j1warren** [comment]
@ocerman, I can confirm.
Thank you!
