### ISSUE TITLE
RAM usage slowly grows over time

### ISSUE THREAD

**Issue by iancuio** [ocerman/zenmonitor#16]
Hello!

First of all I want to thank you for making such an amazing piece of software for us Ryzen users on Ubuntu! :D

Now, a small issue. 

Today I noticed that I had too much RAM occupied in my system monitor. When I ordered the processes by memory usage, I saw that zenmonitor was using **3.2GB of RAM!** (I don't have a screenshot because I closed it)

Closed it, opened it again and saw it start at **~10mb** of RAM. Left it open and studied it a bit and saw the RAM usage **go up by 200-300kb each couple of seconds**. I had my session open for like 12 hours or more and that's how I got to 3.2GB RAM usage.

**Fresh opened zenmonitor:**
![Fresh open zenmonitor](https://user-images.githubusercontent.com/13288065/73564808-0dae4100-4469-11ea-9120-07798fa2ed81.png)

**10 mins of uptime:**
![10 mins of uptime](https://user-images.githubusercontent.com/13288065/73564861-2e769680-4469-11ea-9396-c97f1cab2808.png)

**Comment by ocerman** [comment]
Thanks for your report. I have pushed new commit that should fix that, can you try it?

**Comment by iancuio** [comment]
I will try it tomorrow. I'm using dual-boot and not on Linux now. Will do!

Thanks for being prompt.

**Comment by iancuio** [comment]
Yep! All good an fixed.

**Comment by klikzip** [comment]
commit 523cdc315bbc9486fd8cb0c9cc557e0e0879dbe1 seems to have stopped the Zenmonitor memory leak on my system too. Tracked memory usage over 3 hours and everything seems fine now.
