### ISSUE TITLE
Wrong very high value in Max Package Power

### ISSUE THREAD

**Issue by j1warren** [ocerman/zenmonitor#17]
![zen](https://user-images.githubusercontent.com/46167694/74444583-00338680-4e6d-11ea-8fb5-1419edd09287.png)

I've seen it several times. This is exactly 0xA'0000'0000'0000
If the bug can't be found, maybe put a check for a value to be adequate and discard any value >5000 W, for example.

**Comment by irusanov** [comment]
Yes, I've seen it as well with a 3900X running on Mint 19.3, kernel 5.3.0-28-generic.

**Comment by ocerman** [comment]
Thanks for the report. It has been fixed in the newest version.
