### ISSUE TITLE
Zen 2 

### ISSUE THREAD

**Issue by martinmitrovic** [ocerman/zenmonitor#2]
There seems to be an issue with zen2 
It reports  CPU temperature  Value 206.88c min 206,88c max 206,88c
core voltage -0,043v
soc voltage -0,043
CPU core current 264,998A
CPU core power -11,395 W
SOC Power SVI2 -3,956 Q
Package power 8-9 W

**Comment by ocerman** [comment]
Hello, thanks for your report. This is issue with zenpower driver.
To get this working properly, you need to use last version of zenpower driver and you need to have linux kernel with this patch https://patchwork.kernel.org/patch/11043277/.
Unfortunatelly that patch it's not included yet in kernel 5.2 nor 5.3.
