### ISSUE TITLE
Detects only last 6 cores

### ISSUE THREAD

**Issue by diorn** [ocerman/zenmonitor#20]
Running on linux Mint kernel 5.5.6, threadripper 2970
All is well except for the fact that the frequency of all cores except for the last 6 is not detected (the cores are detected but the frequency displays 0)

**Comment by ocerman** [comment]
Thanks for your report. Can you confirm that you are using latest version (1.4.0) of zenmonitor?

Can you please post output of:
```
tail /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq
```

**Comment by diorn** [comment]
> Yes it is version 1.4.0

this is the output:
==> /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq <==
2866961

==> /sys/devices/system/cpu/cpu10/cpufreq/scaling_cur_freq <==
2880594

==> /sys/devices/system/cpu/cpu11/cpufreq/scaling_cur_freq <==
2804669

==> /sys/devices/system/cpu/cpu12/cpufreq/scaling_cur_freq <==
2813499

==> /sys/devices/system/cpu/cpu13/cpufreq/scaling_cur_freq <==
2883619

==> /sys/devices/system/cpu/cpu14/cpufreq/scaling_cur_freq <==
2867611

==> /sys/devices/system/cpu/cpu15/cpufreq/scaling_cur_freq <==
2630329

==> /sys/devices/system/cpu/cpu16/cpufreq/scaling_cur_freq <==
2808635

==> /sys/devices/system/cpu/cpu17/cpufreq/scaling_cur_freq <==
2864556

==> /sys/devices/system/cpu/cpu18/cpufreq/scaling_cur_freq <==
2892847

==> /sys/devices/system/cpu/cpu19/cpufreq/scaling_cur_freq <==
2911904

==> /sys/devices/system/cpu/cpu1/cpufreq/scaling_cur_freq <==
2862855

==> /sys/devices/system/cpu/cpu20/cpufreq/scaling_cur_freq <==
2904177

==> /sys/devices/system/cpu/cpu21/cpufreq/scaling_cur_freq <==
2888242

==> /sys/devices/system/cpu/cpu22/cpufreq/scaling_cur_freq <==
2906332

==> /sys/devices/system/cpu/cpu23/cpufreq/scaling_cur_freq <==
2885080

==> /sys/devices/system/cpu/cpu24/cpufreq/scaling_cur_freq <==
2932246

==> /sys/devices/system/cpu/cpu25/cpufreq/scaling_cur_freq <==
3010692

==> /sys/devices/system/cpu/cpu26/cpufreq/scaling_cur_freq <==
3009752

==> /sys/devices/system/cpu/cpu27/cpufreq/scaling_cur_freq <==
2794211

==> /sys/devices/system/cpu/cpu28/cpufreq/scaling_cur_freq <==
2921982

==> /sys/devices/system/cpu/cpu29/cpufreq/scaling_cur_freq <==
2977376

==> /sys/devices/system/cpu/cpu2/cpufreq/scaling_cur_freq <==
2935823

==> /sys/devices/system/cpu/cpu30/cpufreq/scaling_cur_freq <==
2902550

==> /sys/devices/system/cpu/cpu31/cpufreq/scaling_cur_freq <==
2862474

==> /sys/devices/system/cpu/cpu32/cpufreq/scaling_cur_freq <==
2853417

==> /sys/devices/system/cpu/cpu33/cpufreq/scaling_cur_freq <==
2878741

==> /sys/devices/system/cpu/cpu34/cpufreq/scaling_cur_freq <==
2843152

==> /sys/devices/system/cpu/cpu35/cpufreq/scaling_cur_freq <==
2863894

==> /sys/devices/system/cpu/cpu36/cpufreq/scaling_cur_freq <==
2859345

==> /sys/devices/system/cpu/cpu37/cpufreq/scaling_cur_freq <==
2874846

==> /sys/devices/system/cpu/cpu38/cpufreq/scaling_cur_freq <==
2913618

==> /sys/devices/system/cpu/cpu39/cpufreq/scaling_cur_freq <==
2942403

==> /sys/devices/system/cpu/cpu3/cpufreq/scaling_cur_freq <==
2965407

==> /sys/devices/system/cpu/cpu40/cpufreq/scaling_cur_freq <==
2975740

==> /sys/devices/system/cpu/cpu41/cpufreq/scaling_cur_freq <==
2957515

==> /sys/devices/system/cpu/cpu42/cpufreq/scaling_cur_freq <==
2942249

==> /sys/devices/system/cpu/cpu43/cpufreq/scaling_cur_freq <==
2927350

==> /sys/devices/system/cpu/cpu44/cpufreq/scaling_cur_freq <==
3003109

==> /sys/devices/system/cpu/cpu45/cpufreq/scaling_cur_freq <==
3054492

==> /sys/devices/system/cpu/cpu46/cpufreq/scaling_cur_freq <==
3045012

==> /sys/devices/system/cpu/cpu47/cpufreq/scaling_cur_freq <==
2937524

==> /sys/devices/system/cpu/cpu4/cpufreq/scaling_cur_freq <==
2825953

==> /sys/devices/system/cpu/cpu5/cpufreq/scaling_cur_freq <==
2820085

==> /sys/devices/system/cpu/cpu6/cpufreq/scaling_cur_freq <==
2507556

==> /sys/devices/system/cpu/cpu7/cpufreq/scaling_cur_freq <==
2938897

==> /sys/devices/system/cpu/cpu8/cpufreq/scaling_cur_freq <==
2883474

==> /sys/devices/system/cpu/cpu9/cpufreq/scaling_cur_freq <==
2883851

**Comment by KeithMyers** [comment]
I have the same issue on a TR 2920X. Only the last six cores report frequency.
Ubuntu 18.04.4 LTS
kernel 5.3.0.53-generic
![Zenpower_missing_freqs](https://user-images.githubusercontent.com/31547850/82929287-42726680-9f38-11ea-9b78-432414d1395e.png)

**Comment by ocerman** [comment]
@KeithMyers thanks for your report. Can you please post output of:
```
tail /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq
```

**Comment by KeithMyers** [comment]
Sure.
keith@Numbskull:~$ tail /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq
==> /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq <==
4099230

==> /sys/devices/system/cpu/cpu10/cpufreq/scaling_cur_freq <==
4098827

==> /sys/devices/system/cpu/cpu11/cpufreq/scaling_cur_freq <==
4099335

==> /sys/devices/system/cpu/cpu12/cpufreq/scaling_cur_freq <==
4099318

==> /sys/devices/system/cpu/cpu13/cpufreq/scaling_cur_freq <==
4098409

==> /sys/devices/system/cpu/cpu14/cpufreq/scaling_cur_freq <==
4099332

==> /sys/devices/system/cpu/cpu15/cpufreq/scaling_cur_freq <==
4099332

==> /sys/devices/system/cpu/cpu16/cpufreq/scaling_cur_freq <==
4099334

==> /sys/devices/system/cpu/cpu17/cpufreq/scaling_cur_freq <==
4099333

==> /sys/devices/system/cpu/cpu18/cpufreq/scaling_cur_freq <==
4099165

==> /sys/devices/system/cpu/cpu19/cpufreq/scaling_cur_freq <==
4099334

==> /sys/devices/system/cpu/cpu1/cpufreq/scaling_cur_freq <==
4099332

==> /sys/devices/system/cpu/cpu20/cpufreq/scaling_cur_freq <==
4099332

==> /sys/devices/system/cpu/cpu21/cpufreq/scaling_cur_freq <==
4099332

==> /sys/devices/system/cpu/cpu22/cpufreq/scaling_cur_freq <==
4099334

==> /sys/devices/system/cpu/cpu23/cpufreq/scaling_cur_freq <==
4099334

==> /sys/devices/system/cpu/cpu2/cpufreq/scaling_cur_freq <==
4099333

==> /sys/devices/system/cpu/cpu3/cpufreq/scaling_cur_freq <==
4099332

==> /sys/devices/system/cpu/cpu4/cpufreq/scaling_cur_freq <==
4098695

==> /sys/devices/system/cpu/cpu5/cpufreq/scaling_cur_freq <==
4099332

==> /sys/devices/system/cpu/cpu6/cpufreq/scaling_cur_freq <==
4099335

==> /sys/devices/system/cpu/cpu7/cpufreq/scaling_cur_freq <==
4099326

==> /sys/devices/system/cpu/cpu8/cpufreq/scaling_cur_freq <==
4099333

==> /sys/devices/system/cpu/cpu9/cpufreq/scaling_cur_freq <==
4099331
keith@Numbskull:~$

**Comment by ocerman** [comment]
@KeithMyers I think I know where is the problem. Just to confirm it, can you please post output of:
```
tail /sys/devices/system/cpu/cpu*/topology/{core_id,die_id}
```

**Comment by KeithMyers** [comment]
Here ya go.
keith@Numbskull:~$ tail /sys/devices/system/cpu/cpu*/topology/{core_id,die_id}
==> /sys/devices/system/cpu/cpu0/topology/core_id <==
0

==> /sys/devices/system/cpu/cpu10/topology/core_id <==
5

==> /sys/devices/system/cpu/cpu11/topology/core_id <==
6

==> /sys/devices/system/cpu/cpu12/topology/core_id <==
0

==> /sys/devices/system/cpu/cpu13/topology/core_id <==
1

==> /sys/devices/system/cpu/cpu14/topology/core_id <==
2

==> /sys/devices/system/cpu/cpu15/topology/core_id <==
4

==> /sys/devices/system/cpu/cpu16/topology/core_id <==
5

==> /sys/devices/system/cpu/cpu17/topology/core_id <==
6

==> /sys/devices/system/cpu/cpu18/topology/core_id <==
0

==> /sys/devices/system/cpu/cpu19/topology/core_id <==
1

==> /sys/devices/system/cpu/cpu1/topology/core_id <==
1

==> /sys/devices/system/cpu/cpu20/topology/core_id <==
2

==> /sys/devices/system/cpu/cpu21/topology/core_id <==
4

==> /sys/devices/system/cpu/cpu22/topology/core_id <==
5

==> /sys/devices/system/cpu/cpu23/topology/core_id <==
6

==> /sys/devices/system/cpu/cpu2/topology/core_id <==
2

==> /sys/devices/system/cpu/cpu3/topology/core_id <==
4

==> /sys/devices/system/cpu/cpu4/topology/core_id <==
5

==> /sys/devices/system/cpu/cpu5/topology/core_id <==
6

==> /sys/devices/system/cpu/cpu6/topology/core_id <==
0

==> /sys/devices/system/cpu/cpu7/topology/core_id <==
1

==> /sys/devices/system/cpu/cpu8/topology/core_id <==
2

==> /sys/devices/system/cpu/cpu9/topology/core_id <==
4

==> /sys/devices/system/cpu/cpu0/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu10/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu11/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu12/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu13/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu14/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu15/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu16/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu17/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu18/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu19/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu1/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu20/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu21/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu22/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu23/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu2/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu3/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu4/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu5/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu6/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu7/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu8/topology/die_id <==
0

==> /sys/devices/system/cpu/cpu9/topology/die_id <==
0
keith@Numbskull:~$

**Comment by ocerman** [comment]
@KeithMyers I think I got it.
Can you try new version from branch sysdet2 https://github.com/ocerman/zenmonitor/tree/sysdet2 ?

**Comment by KeithMyers** [comment]
Looks like the Zenmonitor 1.41 versions does the trick.
![Screenshot of Zenmonitor_1 41](https://user-images.githubusercontent.com/31547850/83975344-498a6480-a8a8-11ea-967f-adb0d72ea4ee.png)

**Comment by ocerman** [comment]
Branch merged to master. Fixed
