### ISSUE TITLE
No temperature for 3700X

### ISSUE THREAD

**Issue by btn21** [ocerman/zenmonitor#3]
Not getting any temperature readings for my 3700X using latest git revision. 
Using your Zen monitor I'm getting 0.00C for tCtrl and tDie
Same result when using psensors

Kernel version 5.2.3
zenmonitor version: 0.1.2 (latest from master branch)

**Comment by Seji64** [comment]
i got the same issue
![Bildschirmfoto vom 2019-07-28 17-42-07](https://user-images.githubusercontent.com/19726119/62009405-0d05bc80-b15f-11e9-9eb4-6664d4db3ea9.png)

**Comment by eVen-gits** [comment]
I have the temperature, but it's wrong.

![image](https://user-images.githubusercontent.com/2612606/62158422-a5db3a00-b30f-11e9-9eb4-c1e09b8c9b31.png)

**Comment by ocerman** [comment]
Hello, thanks for your report. This is issue with zenpower driver.
To get this working properly, you need to use last version of zenpower driver and you need to have linux kernel with this patch https://patchwork.kernel.org/patch/11043277/.
Unfortunatelly that patch is not included yet in kernel 5.2 nor 5.3.

**Comment by eVen-gits** [comment]
Oh thanks for the clarification. I thought only zenpower was needed. Unfortunately, I don't have the know-how to apply this patch so I guess I'll wait until it's included in a stable version.

Thanks for your help!
