### ISSUE TITLE
Zenpower and Zenmonitor data is flipped 

### ISSUE THREAD

**Issue by Rob-bb** [ocerman/zenmonitor#38]
Hi,  Zenpower and Zenmonitor report the Tdie and Tctrl values flipped relative to each other on a threadripper 1950x, as per the picture zenpower says Tdie is 25c and zenmonitor reports 52c

![image](https://user-images.githubusercontent.com/3431318/146994771-ff014400-f057-47ae-943b-3e7c3ccdf9d4.png)

**Comment by KeithMyers** [comment]
I reported this over a year ago.  This repo is not maintained anymore.  The issue was fixed in the new branch here.
[https://github.com/Ta180m/zenmonitor3](url)
The zenpower driver is also not maintained anymore but this new branch is.
[https://github.com/Ta180m/zenpower3](url)

**Comment by Rob-bb** [comment]
> I reported this over a year ago. This repo is not maintained anymore. The issue was fixed in the new branch here.


Thanks for letting me know, I have switched over to the new repos
