### ISSUE TITLE
No Temperature Readings with 1700X (but works in PSensor)

### ISSUE THREAD

**Issue by Jrugia** [ocerman/zenmonitor#4]
Using the zenpower driver I can get a temperature reading in PSensor but not in Zenmonitor. I'm running Kernel 5.0.21.

![Sensors](https://user-images.githubusercontent.com/13750621/62038187-94057400-b1f5-11e9-837e-4818e31b23d8.jpg)

Additionally, running "sensors" in terminal gives the missing info:
![Sensors_2](https://user-images.githubusercontent.com/13750621/62039175-720cf100-b1f7-11e9-8244-cf223f7c432c.jpg)

**Comment by ocerman** [comment]
Hello, thanks for your report. Can you tell me what linux distro are you using?

**Comment by Jrugia** [comment]
Hi, sorry for not responding any sooner, I just got back from vacation.

The distro is Debian 9 (fully updated to 9.9). the kernel is 5.0.21 and has been self compiled.

**Comment by Jrugia** [comment]
I tried to rebuild the program again and noticed some warnings in terminal. Log file attached maybe it will help.

[make_output.txt](https://github.com/ocerman/zenmonitor/files/3476569/make_output.txt)
